#!/bin/bash

# 🔧 Script de configuración para GitHub Actions
echo "🚀 Configurando GitHub Actions para deploy automático..."

echo ""
echo "📋 SECRETOS REQUERIDOS EN GITHUB:"
echo "=================================="
echo ""
echo "1. VPS_HOST: 172.206.16.218"
echo "2. VPS_USER: SOLITARIOfeliz"  
echo "3. VPS_SSH_KEY: [Tu clave SSH privada]"
echo ""

echo "🔐 CÓMO CONFIGURAR LOS SECRETOS:"
echo "==============================="
echo ""
echo "1. Ve a: https://github.com/solitarioo1/MI_AGENTE/settings/secrets/actions"
echo "2. Click en 'New repository secret'"
echo "3. Agrega estos secretos:"
echo ""
echo "   Nombre: VPS_HOST"
echo "   Valor: 172.206.16.218"
echo ""
echo "   Nombre: VPS_USER"  
echo "   Valor: SOLITARIOfeliz"
echo ""
echo "   Nombre: VPS_SSH_KEY"
echo "   Valor: [Contenido de tu clave SSH privada]"
echo ""

echo "🔑 GENERAR CLAVE SSH (si no tienes):"
echo "===================================="
echo ""
echo "En tu VPS ejecuta:"
echo "ssh-keygen -t rsa -b 4096 -C 'github-actions'"
echo "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
echo "cat ~/.ssh/id_rsa  # Copiar esta clave privada al secret VPS_SSH_KEY"
echo ""

echo "✅ DESPUÉS DE CONFIGURAR:"
echo "========================"
echo ""
echo "1. Hacer git push"
echo "2. Ver el deploy automático en:"
echo "   https://github.com/solitarioo1/MI_AGENTE/actions"
echo "3. ¡Nunca más SSH manual!"
echo ""

echo "🎯 FLUJO FINAL:"
echo "=============="
echo "git add ."
echo "git commit -m 'Nueva feature'"
echo "git push origin main"
echo "# 🚀 Deploy automático se ejecuta!"
echo ""